---
title: How to practice
subtitle: Sampling and related issues
bibliography: ../references.bib
---

<!-- COMMENT NOT SHOW IN ANY OUTPUT: Code chunk below sets overall defaults for .qmd file; these inlcude showing output by default and looking for files relative to .Rpoj file, not .qmd file, which makes putting filesin different folders easier  -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
source("../globals.R")
```

## How do make sure you understand this stuff?

Using these skills and applying concepts correctly to interpret data
sets may seem easy when you read about them or listen during class, but
practice is key to ensuring you understand the material. Practice
problems are provided for each lesson. You can make a copy (technically
a *fork*, since you can't directly edit it) of the entire website in
github @
[https://github.com/jsgosnell/cuny_biostats_book](https://github.com/jsgosnell/cuny_biostats_book){target="_blank"}
and work from there. The benefit is this allows you to see updates to
the site (if you sync your fork). The downside is you have to work
interactively or build the entire site when you render a changed file.
This is doable but may take more time than students need. Alternatively,
you can download just the practice problems \@
[https://github.com/jsgosnell/cuny_biostats_practice_problems](https://github.com/jsgosnell/cuny_biostats_practice_problems){target="_blank"}.

**In general you should only work edit .qmd files!  Everything/anything else is produced during the session and should not be edited. All files can be uploaded to github though.** 

Solutions are also provided for all problems via the [course
notes](https://jsgosnell.github.io/cuny_biostats_book/){target="\_blank"},
but try them before you look at the answers!
