---
title: Acknowledgments
---

Many thanks to Bill Rice and Steve Gaines at UCSB for encouraging me to continue
my interests in statistics.  

My department at Baruch also supported me when I  proposed the Biostatistics 
(ENV/BIO 2100) course in 2017 and taught for the 
first time in 2018. 

Baruch College's Center for
Teaching and Learning, as a channel for a  statewide funding effort focuse on 
developed OER (open-educational resources)
at CUNY and SUNY
campuses, have supported the continued development of the class.

The class now includes 

* website (https://sites.google.com/view/biostats/home) housing slides and 
associated material
* tutorials for many lessons using [Swirl](https://swirlstats.com/){target="_blank"}
    * developed with support of a [QUBES working group](https://qubeshub.org/community/groups/teaching_r_fmn){target="_blank"}
* this book!

This repo and GitHub Action was based on the tutorial by Openscapes
[quarto-website-tutorial](https://github.com/Openscapes/quarto-website-tutorial){target="_blank} 
by Julia Lowndes and Stefanie Butland.