---
title: Before the first class
subtitle:  Getting started
date: last-modified
page-layout: full
---

Over the course of the semester/reading this book, our (ambitious) goals are to

-   convince you statistics and data science are a vital component of
    biological, ecological, evolutionary, and medical research
-   help you understand the concepts and linkages among basic tests, so you know
    what they are and when to use each
    -   for undergrad students, that means getting right answers on exams. For
        graduates, this means you'll know how to make decisions about your data
        and communicate/discuss/defend them when talking to advisors and
        reviewers
-   introduce you to tools that are commonly used in the field (and will add to
    your CV) including R (through Rstudio), git, and markdown.
-   make you aware that the skills you learn in this class open the door to
    other careers!

To prepare for our first few lessons

## Concept stuff

-   Check out the class
    [website](https://sites.google.com/view/biostats/home){target="_blank"}
-   Watch [this
    video](https://www.youtube.com/watch?v=sSD84bIkWDw&t=1s){target="_blank"}

## Tech stuff

-   **Get access to R!**. You can make an account at Rstudio cloud
    (https://rstudio.cloud/). You can also install R
    (https://cran.r-project.org/) and Rstudio (https://www.rstudio.com/) on your
    machine, but I **strongly recommend** starting with Rstudio cloud.\
    Rstudio cloud is free for up to 25 hours/month, you don't have to maintain
    it, and it gives gives a standard install (same on all machines, so your
    intro/ our training may be smoother). You can also do both. If you need
    help, videos are at :
    -   [Downloading
        R](https://www.youtube.com/watch?v=S8GrH0MeWkM&list=PLmnVhyQ-20EUFRmsjpYTyB5--zyolr6-o&index=2){target="_blank"}
    -   [Downloading
        Rstudio](https://www.youtube.com/watch?v=pklpCOmK9Cg&list=PLmnVhyQ-20EUFRmsjpYTyB5--zyolr6-o&index=3){target="_blank"}
    -   [Making a Rstudio cloud
        account](https://www.youtube.com/watch?v=ojqNuBRR0y0&list=PLmnVhyQ-20EUFRmsjpYTyB5--zyolr6-o&index=5){target="_blank"}
-   Join the github classroom we'll be using for our sessions
    -   look for email from Blackboard!
        <!--# may need to add open link for outside use -->
    -   When you visit the page it will ask you to connect or create a github
        repository. You can use any name (be anonymous or not) that you want.
        This is a free process.

### Optional (get a head start if you want)

It may be easier to open these intructions in a browser so you can follow along
there while working in Rstudio!

After you join the github classroom, you'll make a clone of the repository onto
your machine. First, find your copy of the repository. You can follow the github
classroom link again, or log into github and then visit
https://github.com/settings/repositories. Find the repository called
data_science_intro_YOURGITHUBUSERNAME, and click on it. Then follow along
below - find instructions for Rstudio cloud or Rstudio desktop depending on your
setup.

#### If you are using Rstudio cloud...

Video at [Accepting your first github repository (from github classroom) and
cloning to **Rstudio
cloud**](https://www.youtube.com/watch?v=GzQ6Dsze8qo&list=PLmnVhyQ-20EUFRmsjpYTyB5--zyolr6-o&index=6){target="_blank"}

Log into your [Rstudio cloud account](https://rstudio.cloud/){target="_blank"}.
You'll see something like this:

![Rstudio cloud home
screen](https://lh3.googleusercontent.com/pw/ACtC-3dVAm8XnMQH9ebnayG0SgBgSewlPFWyJmubIbASefCQ0NKiuZHsQO6eUbzy-Y0LZ6U7KbPkmHCi91tJ4lm7xPs4xf0A3fyMXyMKuzfJ6B2tADIq_NX9GmYRrZS5OuZ6Y1DcCxyzMmmEsV-_DyV9XrLLJA=w1320-h581-no?authuser=0)

To copy a repository, select **New Project**, **New Project from Github repo**.
Next you'll need to enter the url for your repository. To find this, click on
the Code button from the github page for your repository ([instructions
above!](###%20Optional%20(get%20a%20head%20start%20if%20you%20want)))

![Click on Code to get repository
url](https://lh3.googleusercontent.com/pw/ACtC-3c6iXUxY_YkEQktN9szfL0Jfl3-jJnjfp2dwbMU_NtnOtoCOFzJcpRN1r0X0zCZlH2gtB9JlXz7_WLgXMBAU7a2K_vwTX5taNBBWwSgsO558aqLZEtKmH_cMpwv7ukzYi7R4ffncWbcscAy8sAzBcZ4Ww=w692-h490-no?authuser=0)

Copy the web url (or click the copy icon). Input that into the field asking for
the URL of your github repository.

Note you may need to enter your github username and password to create the
repository.

The next screen will bring you to a "normal" RStudio screen. We'll come back to
this in the first class or two!

#### If you are using RStudio on your desktop (or via a server...anywhere that

looks like an RStudio screen)

Video at [Accepting your first github repository (from github classroom) and
cloning to **Rstudio
desktop**](https://www.youtube.com/watch?v=AjrcY0eB54U&list=PLmnVhyQ-20EUFRmsjpYTyB5--zyolr6-o&index=7&t=453s){target="_blank"}

To start working on an assignment, open RStudio.

![Select File \> New Project in
Rstudio](https://lh3.googleusercontent.com/pw/ACtC-3ddyHNvzmRICUa_CmWQmzbz5jr9aTdo_bs9yH9ZbfUPe2LjS46TYj1FsD7CjhKL3rknFZkui-YecWokRGY03cj8occR5HJN56P5N8KJTCUPgciKCAwD8YHJEKXXOOjH-LI8k1G8p88MGB7d_6ov4EJtQQ=w879-h664-no)

Select file, new project, Version control. On the next screen select git. If
this isn't available, you may need to install git (free) on your system. You can
download it at https://git-scm.com/download/.

Next you'll need to enter the url for your repository. To find this, click on
the Code button from the github page for your repository ([instructions
above!](###%20Optional%20(get%20a%20head%20start%20if%20you%20want))).

![Click on Code to get repository
url](https://lh3.googleusercontent.com/pw/ACtC-3c6iXUxY_YkEQktN9szfL0Jfl3-jJnjfp2dwbMU_NtnOtoCOFzJcpRN1r0X0zCZlH2gtB9JlXz7_WLgXMBAU7a2K_vwTX5taNBBWwSgsO558aqLZEtKmH_cMpwv7ukzYi7R4ffncWbcscAy8sAzBcZ4Ww=w692-h490-no?authuser=0)

Copy the web url (or click the copy icon). Input that into the Rstudio
Repository URL space. You can select/edit what you want the repository to be
called and where its stored (its just a folder on your computer). For example, I
have a Repositories folder in my main hard drive where I save all of these. Then
select Create project. Whatever you choose, the project will be saved in new
folder in that location using the name you chose. Note you may need to enter
your github username and password to create the repository.

**You also may get an error/warning about personal access token!** this happens
at different points on different machines (thus why Rstudio cloud is nice). If
you see this now, don't worry. We'll cover it (a known issue) in class.

The next screen will bring you to a "normal" RStudio screen. We'll come back to
this in the first class or two!

\
